// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eytuukuatwpvcwwylrya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5dHV1a3VhdHdwdmN3d3lscnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYxOTYzNDgsImV4cCI6MjA1MTc3MjM0OH0.USLviW1E7C57kYRwQV2NgD-q8KU_GdaxmT4lEBhd1Hw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);